jobs:
    - job: IdentityeApply
      displayName: Identity Apply
      steps:
          - task: TerraformInstaller@0
            displayName: Terraform Install
            inputs:
              terraformVersion: '${{parameters.terraform_version}}'
          - task: TerraformTaskV3@3
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '${{parameters.workingDirectory}}'
              backendServiceArm: '${{parameters.backendServiceArm}}'
              backendAzureRmResourceGroupName: '${{parameters.backendAzureRmResourceGroupName}}'
              backendAzureRmStorageAccountName: '${{parameters.backendAzureRmStorageAccountName}}'
              backendAzureRmContainerName: '${{parameters.backendAzureRmContainerName}}'
              backendAzureRmKey: '${{parameters.backendAzureRmKey}}'
          - task: TerraformTaskV3@3
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '${{paramters.workingDirectory}}'
              environmentServiceNameAzureRM: '${{parameters.backendServiceArm}}'